public class OpportunityTriggerHandler {
    
    public void beforeInsert(List<Opportunity> Opp){
        
    }

    public void beforeUpdate(List<Opportunity> Opp, List<Opportunity> oldOpp){
        
    }
    
    public void beforeDelete(List<Opportunity> Opp){
        
    }
    
    public void afterInsert(List<Opportunity> Opp){
        
    }
    
    public void afterUpdate(List<Opportunity> Opp){
        
    }
    
    public void afterDelete(List<Opportunity> Opp){
        
    }
}